### ISSUE TITLE
Improve style of About page

### ISSUE THREAD

**Issue by jkintana** [DSSD-Madison/madison-website#19]
Check out the about page for DSSD Global for potential designs: https://dssdglobal.org/about

**Comment by jkintana** [comment]
Also: Add in the navbar once it gets made into a component

**Comment by JackBlake-zkq** [comment]
> Also: Add in the navbar once it gets made into a component

We are just going to have the Navbar component in the [page layout](../blob/main/src/layouts/Layout.astro) so that it is on every page. Sarthak is working on it 👍
