### ISSUE TITLE
Implement About Page design

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/madison-website#49]

**Comment by MaxMaeder** [comment]
@JackBlake-zkq could you provide a bit more guidance on what should be on the about page? Rough layout, copy, images, etc? Content kind of matters in how I implement the design

Thanks, Max

**Comment by JackBlake-zkq** [comment]
@MaxMaeder The only content that will be on the page is what's already there. Since it's rich text, I'm pretty sure we can embed images from the Contentful side without having to handle the content differently. The basic design is on the Figma project, although it's quite primarive so feel free to improve it if you are interested.

**Comment by MaxMaeder** [comment]
What styling work should be done on the page then if it is all styled by contentful? Additionally, could I be added to the CMS?
Thanks

**Comment by JackBlake-zkq** [comment]
Just the basic layout to mimic the Figma design. Contentful is really styling anything, I just meant that you can embed images into rich text, so we don't need to change the content model to add images to the about section. 
Unfortunately, the Contentful free tier only allows for 5 members on a team so we can't add any more people to it. You can explore the content model using the Javascript API e.g. the getContentModel function described in the README or something you implement yourself.
